/* Generated By:JavaCC: Do not edit this line. CeylonLexerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CeylonLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KW_SHARED = 7;
  /** RegularExpression Id. */
  int KW_VARIABLE = 8;
  /** RegularExpression Id. */
  int KW_VALUE = 9;
  /** RegularExpression Id. */
  int KW_VOID = 10;
  /** RegularExpression Id. */
  int KW_FUNCTION = 11;
  /** RegularExpression Id. */
  int KW_CLASS = 12;
  /** RegularExpression Id. */
  int KW_INTERFACE = 13;
  /** RegularExpression Id. */
  int KW_OBJECT = 14;
  /** RegularExpression Id. */
  int KW_ASSIGN = 15;
  /** RegularExpression Id. */
  int KW_ABSTRACT = 16;
  /** RegularExpression Id. */
  int KW_ACTUAL = 17;
  /** RegularExpression Id. */
  int KW_FORMAL = 18;
  /** RegularExpression Id. */
  int KW_DEFAULT = 19;
  /** RegularExpression Id. */
  int KW_IMPORT = 20;
  /** RegularExpression Id. */
  int KW_PACKAGE = 21;
  /** RegularExpression Id. */
  int KW_MODULE = 22;
  /** RegularExpression Id. */
  int KW_IF = 23;
  /** RegularExpression Id. */
  int KW_ELSE = 24;
  /** RegularExpression Id. */
  int KW_SWITCH = 25;
  /** RegularExpression Id. */
  int KW_CASE = 26;
  /** RegularExpression Id. */
  int KW_FOR = 27;
  /** RegularExpression Id. */
  int KW_WHILE = 28;
  /** RegularExpression Id. */
  int KW_IN = 29;
  /** RegularExpression Id. */
  int KW_RETURN = 30;
  /** RegularExpression Id. */
  int KW_BREAK = 31;
  /** RegularExpression Id. */
  int KW_CONTINUE = 32;
  /** RegularExpression Id. */
  int KW_TRY = 33;
  /** RegularExpression Id. */
  int KW_CATCH = 34;
  /** RegularExpression Id. */
  int KW_FINALLY = 35;
  /** RegularExpression Id. */
  int KW_THROW = 36;
  /** RegularExpression Id. */
  int KW_IS = 37;
  /** RegularExpression Id. */
  int KW_EXISTS = 38;
  /** RegularExpression Id. */
  int KW_NONEMPTY = 39;
  /** RegularExpression Id. */
  int TYPE_INTEGER = 40;
  /** RegularExpression Id. */
  int TYPE_FLOAT = 41;
  /** RegularExpression Id. */
  int TYPE_STRING = 42;
  /** RegularExpression Id. */
  int TYPE_CHAR = 43;
  /** RegularExpression Id. */
  int TYPE_BOOLEAN = 44;
  /** RegularExpression Id. */
  int TYPE_BYTE = 45;
  /** RegularExpression Id. */
  int TYPE_ANYTHING = 46;
  /** RegularExpression Id. */
  int TYPE_OBJECT = 47;
  /** RegularExpression Id. */
  int TYPE_NULL = 48;
  /** RegularExpression Id. */
  int TYPE_LIST = 49;
  /** RegularExpression Id. */
  int TYPE_MAP = 50;
  /** RegularExpression Id. */
  int OP_SAFE_MEMBER = 51;
  /** RegularExpression Id. */
  int OP_SPREAD_MEMBER = 52;
  /** RegularExpression Id. */
  int OP_ENTRY = 53;
  /** RegularExpression Id. */
  int OP_VARIABLE_ASSIGN = 54;
  /** RegularExpression Id. */
  int OP_ADD_ASSIGN = 55;
  /** RegularExpression Id. */
  int OP_SUB_ASSIGN = 56;
  /** RegularExpression Id. */
  int OP_MUL_ASSIGN = 57;
  /** RegularExpression Id. */
  int OP_DIV_ASSIGN = 58;
  /** RegularExpression Id. */
  int OP_EQUAL = 59;
  /** RegularExpression Id. */
  int OP_NOT_EQUAL = 60;
  /** RegularExpression Id. */
  int OP_LESS_EQUAL = 61;
  /** RegularExpression Id. */
  int OP_GREATER_EQUAL = 62;
  /** RegularExpression Id. */
  int OP_COMPARE = 63;
  /** RegularExpression Id. */
  int OP_DEFAULT = 64;
  /** RegularExpression Id. */
  int OP_RANGE = 65;
  /** RegularExpression Id. */
  int OP_SEGMENT = 66;
  /** RegularExpression Id. */
  int OP_TYPE_CANON = 67;
  /** RegularExpression Id. */
  int OP_INCREMENT = 68;
  /** RegularExpression Id. */
  int OP_DECREMENT = 69;
  /** RegularExpression Id. */
  int OP_SPECIFY = 70;
  /** RegularExpression Id. */
  int OP_MEMBER = 71;
  /** RegularExpression Id. */
  int OP_ADD = 72;
  /** RegularExpression Id. */
  int OP_SUB = 73;
  /** RegularExpression Id. */
  int OP_MUL = 74;
  /** RegularExpression Id. */
  int OP_DIV = 75;
  /** RegularExpression Id. */
  int OP_REMAINDER = 76;
  /** RegularExpression Id. */
  int OP_POWER = 77;
  /** RegularExpression Id. */
  int OP_AND = 78;
  /** RegularExpression Id. */
  int OP_OR = 79;
  /** RegularExpression Id. */
  int OP_NOT = 80;
  /** RegularExpression Id. */
  int OP_LESS = 81;
  /** RegularExpression Id. */
  int OP_GREATER = 82;
  /** RegularExpression Id. */
  int L_PAREN = 83;
  /** RegularExpression Id. */
  int R_PAREN = 84;
  /** RegularExpression Id. */
  int L_BRACKET = 85;
  /** RegularExpression Id. */
  int R_BRACKET = 86;
  /** RegularExpression Id. */
  int L_BRACE = 87;
  /** RegularExpression Id. */
  int R_BRACE = 88;
  /** RegularExpression Id. */
  int COMMA = 89;
  /** RegularExpression Id. */
  int SEMICOLON = 90;
  /** RegularExpression Id. */
  int COLON = 91;
  /** RegularExpression Id. */
  int QUESTION_MARK = 92;
  /** RegularExpression Id. */
  int LIT_TRUE = 93;
  /** RegularExpression Id. */
  int LIT_FALSE = 94;
  /** RegularExpression Id. */
  int LIT_NULL = 95;
  /** RegularExpression Id. */
  int LIT_FLOAT = 96;
  /** RegularExpression Id. */
  int LIT_INT = 97;
  /** RegularExpression Id. */
  int LIT_STRING = 98;
  /** RegularExpression Id. */
  int ID = 99;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"shared\"",
    "\"variable\"",
    "\"value\"",
    "\"void\"",
    "\"function\"",
    "\"class\"",
    "\"interface\"",
    "\"object\"",
    "\"assign\"",
    "\"abstract\"",
    "\"actual\"",
    "\"formal\"",
    "\"default\"",
    "\"import\"",
    "\"package\"",
    "\"module\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\"for\"",
    "\"while\"",
    "\"in\"",
    "\"return\"",
    "\"break\"",
    "\"continue\"",
    "\"try\"",
    "\"catch\"",
    "\"finally\"",
    "\"throw\"",
    "\"is\"",
    "\"exists\"",
    "\"nonempty\"",
    "\"Integer\"",
    "\"Float\"",
    "\"String\"",
    "\"Character\"",
    "\"Boolean\"",
    "\"Byte\"",
    "\"Anything\"",
    "\"Object\"",
    "\"Null\"",
    "\"List\"",
    "\"Map\"",
    "\"?.\"",
    "\"*.\"",
    "\"->\"",
    "\":=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"<=>\"",
    "\"??\"",
    "\"..\"",
    "\"...\"",
    "\"::\"",
    "\"++\"",
    "\"--\"",
    "\"=\"",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"<\"",
    "\">\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"?\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<LIT_FLOAT>",
    "<LIT_INT>",
    "<LIT_STRING>",
    "<ID>",
  };

}
