/* CeylonLexerTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. CeylonLexerTokenManager.java */
import java.io.*;
import java.lang.reflect.*;
import java.util.*;

/** Token Manager. */
@SuppressWarnings ("unused")
public class CeylonLexerTokenManager implements CeylonLexerConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x400000000000000L) != 0L || (active1 & 0x800L) != 0L)
            return 8;
         if ((active0 & 0x7ffffffffff80L) != 0L || (active1 & 0xe0000000L) != 0L)
         {
            jjmatchedKind = 99;
            return 6;
         }
         return -1;
      case 1:
         if ((active0 & 0x7ffdfdf7fdf80L) != 0L || (active1 & 0xe0000000L) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 99;
               jjmatchedPos = 1;
            }
            return 6;
         }
         if ((active0 & 0x2020802000L) != 0L)
            return 6;
         return -1;
      case 2:
         if ((active0 & 0x4000208040000L) != 0L)
            return 6;
         if ((active0 & 0x3ffddd77bff80L) != 0L || (active1 & 0xe0000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 99;
               jjmatchedPos = 2;
            }
            return 6;
         }
         return -1;
      case 3:
         if ((active0 & 0x3200005000400L) != 0L || (active1 & 0xa0000000L) != 0L)
            return 6;
         if ((active0 & 0xdfddd27ffb80L) != 0L || (active1 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 3;
            return 6;
         }
         return -1;
      case 4:
         if ((active0 & 0x21490001200L) != 0L || (active1 & 0x40000000L) != 0L)
            return 6;
         if ((active0 & 0xddc9427fe980L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 4;
            return 6;
         }
         return -1;
      case 5:
         if ((active0 & 0x84404256c080L) != 0L)
            return 6;
         if ((active0 & 0x598900292900L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 5;
            return 6;
         }
         return -1;
      case 6:
         if ((active0 & 0x110800280000L) != 0L)
            return 6;
         if ((active0 & 0x488100012900L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 6;
            return 6;
         }
         return -1;
      case 7:
         if ((active0 & 0x408100010900L) != 0L)
            return 6;
         if ((active0 & 0x80000002000L) != 0L)
         {
            jjmatchedKind = 99;
            jjmatchedPos = 7;
            return 6;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         jjmatchedKind = 80;
         return jjMoveStringLiteralDfa1_0(0x1000000000000000L, 0x0L);
      case 37:
         return jjStopAtPos(0, 76);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x4000L);
      case 40:
         return jjStopAtPos(0, 83);
      case 41:
         return jjStopAtPos(0, 84);
      case 42:
         jjmatchedKind = 74;
         return jjMoveStringLiteralDfa1_0(0x210000000000000L, 0x0L);
      case 43:
         jjmatchedKind = 72;
         return jjMoveStringLiteralDfa1_0(0x80000000000000L, 0x10L);
      case 44:
         return jjStopAtPos(0, 89);
      case 45:
         jjmatchedKind = 73;
         return jjMoveStringLiteralDfa1_0(0x120000000000000L, 0x20L);
      case 46:
         jjmatchedKind = 71;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x6L);
      case 47:
         jjmatchedKind = 75;
         return jjMoveStringLiteralDfa1_0(0x400000000000000L, 0x0L);
      case 58:
         jjmatchedKind = 91;
         return jjMoveStringLiteralDfa1_0(0x40000000000000L, 0x8L);
      case 59:
         return jjStopAtPos(0, 90);
      case 60:
         jjmatchedKind = 81;
         return jjMoveStringLiteralDfa1_0(0xa000000000000000L, 0x0L);
      case 61:
         jjmatchedKind = 70;
         return jjMoveStringLiteralDfa1_0(0x800000000000000L, 0x0L);
      case 62:
         jjmatchedKind = 82;
         return jjMoveStringLiteralDfa1_0(0x4000000000000000L, 0x0L);
      case 63:
         jjmatchedKind = 92;
         return jjMoveStringLiteralDfa1_0(0x8000000000000L, 0x1L);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x400000000000L, 0x0L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x300000000000L, 0x0L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x80000000000L, 0x0L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x20000000000L, 0x0L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x10000000000L, 0x0L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x2000000000000L, 0x0L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x4000000000000L, 0x0L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L, 0x0L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x800000000000L, 0x0L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x40000000000L, 0x0L);
      case 91:
         return jjStopAtPos(0, 85);
      case 93:
         return jjStopAtPos(0, 86);
      case 94:
         return jjStopAtPos(0, 77);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x38000L, 0x0L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x80000000L, 0x0L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x504001000L, 0x0L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x80000L, 0x0L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x4001000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x808040800L, 0x40000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x2020902000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x400000L, 0x0L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x8000000000L, 0x80000000L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x4000L, 0x0L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x200000L, 0x0L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x40000000L, 0x0L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x2000080L, 0x0L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x1200000000L, 0x20000000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x700L, 0x0L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x10000000L, 0x0L);
      case 123:
         return jjStopAtPos(0, 87);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x8000L);
      case 125:
         return jjStopAtPos(0, 88);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active1 & 0x4000L) != 0L)
            return jjStopAtPos(1, 78);
         break;
      case 43:
         if ((active1 & 0x10L) != 0L)
            return jjStopAtPos(1, 68);
         break;
      case 45:
         if ((active1 & 0x20L) != 0L)
            return jjStopAtPos(1, 69);
         break;
      case 46:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStopAtPos(1, 51);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStopAtPos(1, 52);
         else if ((active1 & 0x2L) != 0L)
         {
            jjmatchedKind = 65;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x4L);
      case 58:
         if ((active1 & 0x8L) != 0L)
            return jjStopAtPos(1, 67);
         break;
      case 61:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStopAtPos(1, 54);
         else if ((active0 & 0x80000000000000L) != 0L)
            return jjStopAtPos(1, 55);
         else if ((active0 & 0x100000000000000L) != 0L)
            return jjStopAtPos(1, 56);
         else if ((active0 & 0x200000000000000L) != 0L)
            return jjStopAtPos(1, 57);
         else if ((active0 & 0x400000000000000L) != 0L)
            return jjStopAtPos(1, 58);
         else if ((active0 & 0x800000000000000L) != 0L)
            return jjStopAtPos(1, 59);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStopAtPos(1, 60);
         else if ((active0 & 0x2000000000000000L) != 0L)
         {
            jjmatchedKind = 61;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x4000000000000000L) != 0L)
            return jjStopAtPos(1, 62);
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000000000000L, active1, 0L);
      case 62:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStopAtPos(1, 53);
         break;
      case 63:
         if ((active1 & 0x1L) != 0L)
            return jjStopAtPos(1, 64);
         break;
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000404200300L, active1, 0x40000000L);
      case 98:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000014000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x40080000L, active1, 0L);
      case 102:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(1, 23, 6);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x81010000080L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000800000000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x20001001000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000L, active1, 0L);
      case 110:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x410000002000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x108108440400L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x280000000L, active1, 0x20000000L);
      case 115:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 37, 6);
         return jjMoveStringLiteralDfa2_0(active0, 0x8000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000800L, active1, 0x80000000L);
      case 119:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L, active1, 0L);
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x200000000000L, active1, 0L);
      case 124:
         if ((active1 & 0x8000L) != 0L)
            return jjStopAtPos(1, 79);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(0, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1);
      return 2;
   }
   switch(curChar)
   {
      case 46:
         if ((active1 & 0x4L) != 0L)
            return jjStopAtPos(2, 66);
         break;
      case 62:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStopAtPos(2, 63);
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000001080L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000L, active1, 0L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000000L, active1, 0L);
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x4012000400L, active1, 0L);
      case 106:
         return jjMoveStringLiteralDfa3_0(active0, 0x800000004000L, active1, 0L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000200L, active1, 0xc0000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x8900000800L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x120000000000L, active1, 0L);
      case 112:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 50, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x100000L, active1, 0L);
      case 114:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x41000040100L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000005018000L, active1, 0L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x210440022000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x20000000L);
      case 121:
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(2, 33, 6);
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(1, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x20880080000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000800L, active1, 0L);
      case 100:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 6);
         break;
      case 101:
         if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(3, 24, 6);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(3, 26, 6);
         else if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 45, 6);
         else if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(3, 93, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x818000006000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000008100L, active1, 0L);
      case 107:
         return jjMoveStringLiteralDfa4_0(active0, 0x200000L, active1, 0L);
      case 108:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 48, 6);
         else if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(3, 95, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x100010000000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000100000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000080L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000001000L, active1, 0x40000000L);
      case 116:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 49, 6);
         return jjMoveStringLiteralDfa4_0(active0, 0x400102010000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x40420200L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(2, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1);
      return 4;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000260100L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0x800002004000L, active1, 0L);
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 6);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 6);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(4, 94, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000080L, active1, 0L);
      case 103:
         return jjMoveStringLiteralDfa5_0(active0, 0x10000008000L, active1, 0L);
      case 104:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L, active1, 0L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000L, active1, 0L);
      case 107:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 6);
         break;
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x800400000L, active1, 0L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L, active1, 0L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x40112000L, active1, 0L);
      case 115:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(4, 12, 6);
         break;
      case 116:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 41, 6);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000800L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000L, active1, 0L);
      case 119:
         if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 36, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(3, old0, old1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, 0L);
      return 5;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000010000L);
      case 98:
         return jjMoveStringLiteralDfa6_0(active0, 0x100L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000L);
      case 100:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(5, 7, 6);
         break;
      case 101:
         if ((active0 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(5, 22, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x10000000000L);
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000L);
      case 103:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 42, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x200000L);
      case 104:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(5, 25, 6);
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000000800L);
      case 108:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(5, 17, 6);
         else if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(5, 18, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x800080000L);
      case 110:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 6);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(5, 30, 6);
         return jjMoveStringLiteralDfa6_0(active0, 0x100000000L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000000L);
      case 115:
         if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 38, 6);
         break;
      case 116:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 6);
         else if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(5, 20, 6);
         else if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 47, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0, 0L);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, 0L);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x10000L);
      case 101:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 21, 6);
         break;
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x100L);
      case 110:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 44, 6);
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x800L);
      case 114:
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 40, 6);
         break;
      case 116:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(6, 19, 6);
         return jjMoveStringLiteralDfa7_0(active0, 0x88000000000L);
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L);
      case 121:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(6, 35, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(5, active0, 0L);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, 0L);
      return 7;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000L);
      case 101:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(7, 8, 6);
         else if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(7, 32, 6);
         return jjMoveStringLiteralDfa8_0(active0, 0x80000000000L);
      case 103:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 46, 6);
         break;
      case 110:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(7, 11, 6);
         break;
      case 116:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(7, 16, 6);
         break;
      case 121:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 39, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0, 0L);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(8, 13, 6);
         break;
      case 114:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 43, 6);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 27;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 97)
                        kind = 97;
                     { jjCheckNAddStates(0, 2); }
                  }
                  else if (curChar == 47)
                     { jjAddStates(3, 4); }
                  else if (curChar == 34)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 8:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(14, 15); }
                  else if (curChar == 47)
                  {
                     if (kind > 5)
                        kind = 5;
                     { jjCheckNAddStates(8, 10); }
                  }
                  break;
               case 1:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 3:
                  if ((0x8400000000L & l) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 4:
                  if (curChar == 34 && kind > 98)
                     kind = 98;
                  break;
               case 6:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 99)
                     kind = 99;
                  jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 7:
                  if (curChar == 47)
                     { jjAddStates(3, 4); }
                  break;
               case 9:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjCheckNAddStates(8, 10); }
                  break;
               case 10:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 11:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 12:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(14, 15); }
                  break;
               case 14:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(14, 15); }
                  break;
               case 15:
                  if (curChar == 42)
                     { jjAddStates(11, 12); }
                  break;
               case 16:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(17, 15); }
                  break;
               case 17:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(17, 15); }
                  break;
               case 18:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 97)
                     kind = 97;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(20, 21); }
                  break;
               case 21:
                  if (curChar == 46)
                     { jjCheckNAdd(22); }
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 96)
                     kind = 96;
                  { jjCheckNAddTwoStates(22, 23); }
                  break;
               case 24:
                  if ((0x280000000000L & l) != 0L)
                     { jjCheckNAdd(25); }
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 96)
                     kind = 96;
                  { jjCheckNAdd(25); }
                  break;
               case 26:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 97)
                     kind = 97;
                  { jjCheckNAdd(26); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 0:
               case 6:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 99)
                     kind = 99;
                  { jjCheckNAdd(6); }
                  break;
               case 1:
                  if ((0xffffffffefffffffL & l) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 2:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if ((0x14404410000000L & l) != 0L)
                     { jjCheckNAddStates(5, 7); }
                  break;
               case 9:
                  if (kind > 5)
                     kind = 5;
                  { jjAddStates(8, 10); }
                  break;
               case 14:
                  { jjCheckNAddTwoStates(14, 15); }
                  break;
               case 16:
               case 17:
                  { jjCheckNAddTwoStates(17, 15); }
                  break;
               case 23:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(13, 14); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(5, 7); }
                  break;
               case 9:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 5)
                     kind = 5;
                  { jjAddStates(8, 10); }
                  break;
               case 14:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(14, 15); }
                  break;
               case 16:
               case 17:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(17, 15); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 27 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\163\150\141\162\145\144", 
"\166\141\162\151\141\142\154\145", "\166\141\154\165\145", "\166\157\151\144", 
"\146\165\156\143\164\151\157\156", "\143\154\141\163\163", "\151\156\164\145\162\146\141\143\145", 
"\157\142\152\145\143\164", "\141\163\163\151\147\156", "\141\142\163\164\162\141\143\164", 
"\141\143\164\165\141\154", "\146\157\162\155\141\154", "\144\145\146\141\165\154\164", 
"\151\155\160\157\162\164", "\160\141\143\153\141\147\145", "\155\157\144\165\154\145", "\151\146", 
"\145\154\163\145", "\163\167\151\164\143\150", "\143\141\163\145", "\146\157\162", 
"\167\150\151\154\145", "\151\156", "\162\145\164\165\162\156", "\142\162\145\141\153", 
"\143\157\156\164\151\156\165\145", "\164\162\171", "\143\141\164\143\150", "\146\151\156\141\154\154\171", 
"\164\150\162\157\167", "\151\163", "\145\170\151\163\164\163", "\156\157\156\145\155\160\164\171", 
"\111\156\164\145\147\145\162", "\106\154\157\141\164", "\123\164\162\151\156\147", 
"\103\150\141\162\141\143\164\145\162", "\102\157\157\154\145\141\156", "\102\171\164\145", 
"\101\156\171\164\150\151\156\147", "\117\142\152\145\143\164", "\116\165\154\154", "\114\151\163\164", 
"\115\141\160", "\77\56", "\52\56", "\55\76", "\72\75", "\53\75", "\55\75", "\52\75", 
"\57\75", "\75\75", "\41\75", "\74\75", "\76\75", "\74\75\76", "\77\77", "\56\56", 
"\56\56\56", "\72\72", "\53\53", "\55\55", "\75", "\56", "\53", "\55", "\52", "\57", "\45", 
"\136", "\46\46", "\174\174", "\41", "\74", "\76", "\50", "\51", "\133", "\135", 
"\173", "\175", "\54", "\73", "\72", "\77", "\164\162\165\145", 
"\146\141\154\163\145", "\156\165\154\154", null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   20, 21, 26, 8, 13, 1, 2, 4, 9, 10, 12, 16, 18, 24, 25, 
};

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public CeylonLexerTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public CeylonLexerTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 27; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffff81L, 0xfffffffffL, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[27];
    private final int[] jjstateSet = new int[2 * 27];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
